-- cleanup
USE ROLE ACCOUNTADMIN;
DROP DATABASE IF EXISTS ACME_DB_DEV CASCADE;
DROP WAREHOUSE IF EXISTS ACME_ELT_DEV;
DROP WAREHOUSE IF EXISTS ACME_APP_DEV;

DROP ROLE IF EXISTS ACME_SYSADMIN_DEV;
DROP ROLE IF EXISTS ACME_ELT_DEV;
DROP ROLE IF EXISTS ACME_APP_DEV;
DROP ROLE IF EXISTS ACME_RW_DEV;
DROP ROLE IF EXISTS ACME_RO_DEV;

-- create roles
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE ACME_SYSADMIN_DEV;
CREATE OR REPLACE ROLE ACME_ELT_DEV;
CREATE OR REPLACE ROLE ACME_APP_DEV;
CREATE OR REPLACE ROLE ACME_RW_DEV;
CREATE OR REPLACE ROLE ACME_RO_DEV;
 
-- create the hierarchy of roles
GRANT ROLE ACME_RO_DEV TO ROLE ACME_RW_DEV;
GRANT ROLE ACME_RW_DEV TO ROLE ACME_ELT_DEV;
GRANT ROLE ACME_RO_DEV TO ROLE ACME_APP_DEV;
GRANT ROLE ACME_ELT_DEV TO ROLE ACME_SYSADMIN_DEV;
GRANT ROLE ACME_APP_DEV TO ROLE ACME_SYSADMIN_DEV;
GRANT ROLE ACME_SYSADMIN_DEV TO ROLE SYSADMIN;
 
USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE ACME_SYSADMIN_DEV;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE ACME_SYSADMIN_DEV;
 
-- create databases and objects, and grant access rights
USE ROLE ACME_SYSADMIN_DEV;
CREATE DATABASE ACME_DB_DEV;
GRANT USAGE ON DATABASE ACME_DB_DEV TO ROLE ACME_RW_DEV;
GRANT USAGE ON DATABASE ACME_DB_DEV TO ROLE ACME_RO_DEV;
 
CREATE SCHEMA ACME_DB_DEV.ACME_SCH_DEV;
GRANT USAGE ON SCHEMA ACME_DB.ACME_SCH_DEV TO ROLE ACME_RO_DEV;
GRANT USAGE ON SCHEMA ACME_DB_DEV.ACME_SCH_DEV TO ROLE ACME_RW_DEV;
 
GRANT USAGE ON SCHEMA ACME_DB_DEV.PUBLIC TO ROLE ACME_RO_DEV;
GRANT USAGE ON SCHEMA ACME_DB_DEV.PUBLIC TO ROLE ACME_RW_DEV;
 
-- create warehouses, and grant access rights
USE ROLE ACME_SYSADMIN_DEV;
CREATE WAREHOUSE ACME_ELT_DEV WAREHOUSE_SIZE = XSMALL;
GRANT OPERATE, USAGE ON WAREHOUSE ACME_ELT_DEV TO ROLE ACME_ELT_DEV;
 
CREATE WAREHOUSE ACME_APP_DEV WAREHOUSE_SIZE = SMALL;
GRANT OPERATE, USAGE ON WAREHOUSE ACME_APP_DEV TO ROLE ACME_APP_DEV;
 
-- grant rights on future tables
GRANT SELECT ON FUTURE TABLES
  IN SCHEMA ACME_DB_DEV.ACME_SCH_DEV TO ROLE ACME_RO_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES
  IN SCHEMA ACME_DB_DEV.ACME_SCH_DEV TO ROLE ACME_RW_DEV;

-- revoke rights of the tenant SYSADMIN
USE ROLE ACCOUNTADMIN;
REVOKE CREATE DATABASE ON ACCOUNT FROM ROLE ACME_SYSADMIN_DEV;
REVOKE CREATE WAREHOUSE ON ACCOUNT FROM ROLE ACME_SYSADMIN_DEV;
