USE ROLE ACCOUNTADMIN;
DROP DATABASE IF EXISTS ACME_DB_DEV CASCADE;
DROP WAREHOUSE IF EXISTS ACME_ELT_DEV;
DROP WAREHOUSE IF EXISTS ACME_APP_DEV;

DROP ROLE IF EXISTS ACME_SYSADMIN_DEV;
DROP ROLE IF EXISTS ACME_ELT_DEV;
DROP ROLE IF EXISTS ACME_APP_DEV;
DROP ROLE IF EXISTS ACME_RW_DEV;
DROP ROLE IF EXISTS ACME_RO_DEV;